requirejs.config({
	"paths":{
		"jquery":'../js/jquery.min',
		"bootstrap":'../js/bootstrap.min',
		'lodash':'../js/lodash.min',
		'layer':'../js/layer',
		'langs':'../js/langs',
		'react':'../js/react-with-addons',
		'jsxTransformer':'../js/JSXTransformer',
		'reflux':'../js/reflux.min',
		'react-router':'../js/react-router.min',
		'validator':'../js/jquery.validate.min',
		'app':'../dist/'
	}
});